version: '3.9'

services:
  recipe:
    image: recipe
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8000:8000
    command: >
      sh -c ". .venv/bin/activate &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
    - DB_HOST=postgresdb
    - DB_NAME=apidemo
    - DB_USER=apidemo
    - DB_PASS=apidemo
    - DB_PORT=5432
    - REDIS_LOCATION=redis://redis:6379
    - EMAIL_HOST=mailpit
    - EMAIL_PORT=1025
    #- EMAIL_HOST_USER
    #- EMAIL_HOST_PASSWORD
    #- EMAIL_USE_TLS
    #- EMAIL_USE_SSL
    depends_on:
    - postgresdb

  postgresdb:
    image: postgres
    #image: postgres:15-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=apidemo
    - POSTGRES_USER=apidemo
    - POSTGRES_PASSWORD=apidemo
#   redis:
#     image: redis:7-alpine
#     volumes:
#       - redisdata:/data
#     command: redis-server --save 60 1 --loglevel warning
#   redis-commander:
#     #container_name: redis-commander
#     #hostname: redis-commander
#     image: ghcr.io/joeferner/redis-commander:latest
#     restart: always
#     environment:
#     - REDIS_HOSTS=local:redis:6379
#     ports:
#     - "8081:8081"
#     depends_on:
#       - redis
#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - "8888:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@example.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#       PGADMIN_DISABLE_POSTFIX: True
#       PGADMIN_CONFIG_MAIL_SERVER: '"mailpit"'
#       PGADMIN_CONFIG_MAIL_PORT: 1025
#     volumes:
#       - pgadmindata:/var/lib/pgadmin
#     depends_on:
#       - postgresdb
#       - mailpit
#   mailpit:
#     image: axllent/mailpit
#     ports:
#       - 8025:8025
#     environment:
#       - POSTGRES_DB=apidemo
#       - POSTGRES_USER=apidemo
#       - POSTGRES_PASSWORD=apidemo

# volumes:
#   pgdata:
#   pgadmindata:
#   redisdata:
